nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 0 >./17_infer_trial1_seed0.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 1 >./17_infer_trial1_seed1.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 2 >./17_infer_trial1_seed2.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 3 >./17_infer_trial1_seed3.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 4 >./17_infer_trial1_seed4.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 5 >./17_infer_trial1_seed5.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 6 >./17_infer_trial1_seed6.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 7 >./17_infer_trial1_seed7.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 8 >./17_infer_trial1_seed8.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 9 >./17_infer_trial1_seed9.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 10 >./17_infer_trial1_seed10.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 11 >./17_infer_trial1_seed11.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 12 >./17_infer_trial1_seed12.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 13 >./17_infer_trial1_seed13.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 14 >./17_infer_trial1_seed14.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 15 >./17_infer_trial1_seed15.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 16 >./17_infer_trial1_seed16.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 17 >./17_infer_trial1_seed17.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 18 >./17_infer_trial1_seed18.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 19 >./17_infer_trial1_seed19.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 20 >./17_infer_trial1_seed20.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 21 >./17_infer_trial1_seed21.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 22 >./17_infer_trial1_seed22.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 23 >./17_infer_trial1_seed23.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 24 >./17_infer_trial1_seed24.log 2>&1 </dev/null &
nohup python -u _17_infer_log.py --save_folder './time_log0/' --seed 25 >./17_infer_trial1_seed25.log 2>&1 </dev/null &
